### ISSUE TITLE
Examples from README.md modified (so no bug)

### ISSUE THREAD

**Issue by pluim003** [snowienator/Home-Assistant-Prijsplafond#6]
In my template.yaml I added

```
  - sensor:

      # Template sensor to display the current monthly cap.
      - name: 'Prijsplafond monthly gas cap'
        unit_of_measurement: "m.."
        state: "{{ state_attr('sensor.prijsplafond_gas', 'this_month_cap') }}"

      - name: 'Prijsplafond monthly power cap'
        unit_of_measurement: "kWh"
        state: "{{ state_attr('sensor.prijsplafond_power', 'this_month_cap') }}"

```

Had to replace value_template by state and remove the friendly-name as it isn't being used (anymore).

Based on these values and the current monthly usage it should be possible to make sensors for remaining gas and power for current month

Maybe someone knows how to get that correct in the code below:

````
     - name: 'Prijsplafond remaining gas'
        unit_of_measurement: "m.."
        state: "{{ state_attr('sensor.prijsplafond_gas', 'this_month_cap') -
                   states('sensor.prijsplafond_gas') }} "

      - name: 'Prijsplafond remaining power'
        unit_of_measurement: "kWh"
        state: "{{ state_attr('sensor.prijsplafond_power', 'this_month_cap') -
                   states('sensor.prijsplafond_power') }}"

````

**Comment by snowienator** [comment]
Oh yes.. Someone already mensioned I used the old code style.. I usually don't use templates. Will write an example for you.

**Comment by pluim003** [comment]
Succeeded:

```` 
      - name: 'Prijsplafond remaining gas'
        unit_of_measurement: "m.."
        state: "{{ (state_attr('sensor.prijsplafond_gas', 'this_month_cap') | float | round(2) ) -
                   (states('sensor.prijsplafond_gas') | float | round(2) ) }} "
       icon: mdi:gas-cylinder

      - name: 'Prijsplafond remaining power'
        unit_of_measurement: "kWh"
        state: "{{ (state_attr('sensor.prijsplafond_power', 'this_month_cap') | float | round(2) ) -
                   (states('sensor.prijsplafond_power') | float | round(2) ) }}"
        icon: mdi:flash

```` 

Translates to:

![afbeelding](https://user-images.githubusercontent.com/67138922/214071096-6f29f518-969f-49c0-b895-4e9eacf75e97.png)

Except for being the values off but next month it will/might then be OK.

**Comment by snowienator** [comment]
You mind if I copy your code to the readme?

**Comment by pluim003** [comment]
I don't mind. We're here to help each other.

**Comment by larsoss** [comment]
how do u see those entities? i have only 2

**Comment by snowienator** [comment]
The integration provides 2 sensors with attributes like current cap and costs. The info @pluim003 is showing is from the template sensors as described by the given code.

**Comment by pluim003** [comment]
> how do u see those entities? i have only 2

The integration has 2 entities. The 2 sensors in the first screenshot I have put in my template.yaml, as well as the 2 from the second screenshot. Then added to the Lovelace-dashboard.

**Comment by MrPePperNL** [comment]
Just to chime in,

I think this integration and also these template sensors are using the wrong names for the enities.

It's the well known confusion between Power and Energy.

Electrical Power is measured in Watts (W) and Electrical Energy is measured in kiloWatt-hour (kWh).

Clearly we need to use use Energy instead of Power. 

[Info Here](https://www.home-assistant.io/docs/energy/faq/)

**Comment by snowienator** [comment]
@MrPePperNL You are completely right 👍. will rename the friendly names

**Comment by snowienator** [comment]
Config flow is renamed in last release. Will do the entity data later on.

**Comment by mbino** [comment]
![afbeelding](https://user-images.githubusercontent.com/8835353/215375627-59982115-0d67-4fcc-b18a-6f19d325616b.png)
I'm getting at least 2 fields without data after using the template in the README

**Comment by pluim003** [comment]
Some additions:

A few sensors to find out the last day of the current month, number of days until start of next month. 

```
# sensors to find out last day of month and number of days until start of next month to be used with prijsplafond 

  - sensor:
      - name: Last Day of the Month
        icon: mdi:calendar
        #state: "{{ (now() + timedelta(days=1)).day == 1 }}"
        state: "{{ ((now().replace(day=28) + timedelta(days=4)).replace(day=1) - timedelta(days=1)).day }}"
    #    state: "{{ 31 if now().month == 12 else (now().replace(month=now().month+1, day=1) - timedelta(days=1)).day }}"
      
      - name: Current Day
        icon: mdi:calendar
        state: "{{ now().day }}"

      - name: Days until next Month
        icon: mdi:calendar
       # state: "{{ sensor.last_day_of_the_month - sensor.current_day +1 }}"
        state: "{{ states('sensor.last_day_of_the_month')|int(default=0) - states('sensor.current_day')|int(default=0) +1 }}" 

```
And these can be used with:

```
      - name: 'Prijsplafond remaining gas per day current month'
        unit_of_measurement: "m³"
        state: "{{ (states('sensor.prijsplafond_remaining_gas') | float | round(2) / states('sensor.days_until_next_month') | int ) | float | round(2) }}"
        icon: mdi:gas-cylinder                                                                           

      - name: 'Prijsplafond remaining power per day current month'
        unit_of_measurement: "kWh"
        state: "{{ (states('sensor.prijsplafond_remaining_power') | float | round(2) / states('sensor.days_until_next_month') | int ) | float | round(2) }}"
        icon: mdi:flash
```

Today it works, but don't know yet if it will work on a new day. And I had to use the +1, otherwise on the last day of the month it would result in a division by 0. It gives an estimate of what you are 'allowed' to use per day to stay below the prijsplafond-cap-values.

Unfortunately I can't get the m³ in the terminal when editing the yaml-files.
